### ISSUE TITLE
how do i fix this

### ISSUE THREAD

**Issue by waw0** [imvast/Discord-Account-Creator#192]
maybe its my python version but 

Traceback (most recent call last):
  File "C:\Users\no\OneDrive\Pictrues\Desktop\Discord-Account-Creator-main\main.py", line 12, in <module>
    from veilcord    import Solver
  File "C:\Users\no\AppData\Local\Programs\Python\Python311\Lib\site-packages\veilcord\__init__.py", line 5, in <module>
    from .__main__    import *
  File "C:\Users\chebu\AppData\Local\Programs\Python\Python311\Lib\site-packages\veilcord\__main__.py", line 16, in <module>
    from httpx        import get
ModuleNotFoundError: No module named 'httpx'

how do i fix this

**Comment by TeemSucks** [comment]
run `pip3 install httpx`

**Comment by waw0** [comment]
> run `pip3 install httpx`

ty man but ts keeps gettin errors 😭 
got a new one updated in the issue
