### ISSUE TITLE
Error main.py

### ISSUE THREAD

**Issue by aruping** [imvast/Discord-Account-Creator#208]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from veilcord    import Solver
  File "/usr/local/lib/python3.7/site-packages/veilcord/__init__.py", line 1, in <module>
    from .__main__    import *
  File "/usr/local/lib/python3.7/site-packages/veilcord/__main__.py", line 4, in <module>
    from typing       import Optional, Literal
ImportError: cannot import name 'Literal' from 'typing' (/usr/local/lib/python3.7/typing.py)

**Comment by imvast** [comment]
learn how to read the readme 🥱
